<!-- About -->

  <table align="center" border="0">  
    <tr>
      <td valign=top>
        <img src="http://62.195.19.164/perihelion/images/backgrounds/perihelion.jpg">
      </td>  
      <td bgcolor="black" valign="top">
        <table align="center" border="0" width="400" bgcolor="black">
          <tr><th>What is Perihelion?</td></tr>
          <tr><td>
            Perihelion is an so-called online realtime strategy space simulator. In normal english it means that
            this game will be about creating and maintaining an empire somewhere in outer space.<br>
            <br>
            Every player starts with his/her own planet and a small population. From here you can explore the
            galaxy, invent new buildings, products and vessels and even find other races. 
            All things you do are done in realtime, which means that if you construct a vessel, you will have
            to wait a while before that vessel is completed. If you want to fly a vessel to the other side of the
            galaxy, make sure you have a lot of time on your hand. Things takes time in real life, and so do they
            in perihelion. Only we do it a little bit quicker. Note: Travelling from one side from the galaxy to
            the other side with the fastest possible ship, which is the longest journey will make you wait for 
            about 2000 ticks (1 tick is about 10 minuts). So you will have to wait 2 weeks before you are at 
            the other side. :)<br>
            <br>            
            
            <li><b>What's makes this game different from all the others?</b><br>
            I honestly don't know because I never played any games like this before. This idea came to mind a few years
            ago when I was forced to abandon perl as a webscripting language and had to use PHP for a project. The best
            way to learn PHP was to create something and that was a simple - non-working - version of the game called 
            Project X (since it was a nameless project). After a few years, I stumbled upon the project again, and
            started to modify and expand the game until it was becoming Perihelion. <br>            
            <br>
                        
            <li><b>What's possible in the game?</b><br>
            Pretty much everything. The game is divided in multiple galaxies where each galaxy can host about 200 
            players according to the latest tests. All galaxies can be totaly customized: different kinds of ores, 
            different inventions, vessels and buildings.<br>
            In every galaxy everyone has complete freedom on how to play the game. There are 4 different score-rankings
            so everybody can achieve different goals inside the same game.<br>
            <br>
            
            <li><b>How's the gameplay?</b><br>
            Excellent, since we don't need a fancy 3d card, no 1GB physical memory, no loads of diskspace, no fast 
            PC, no nothing. The only thing you will need is an internet connection and a webbrowser.<br>
            At this moment, a put in a lot of effort to make sure the game is playable in not only MSIE6 but also in
            other browsers like Netscape, Opera and even in Links. (ok, the index page is a little bit MSIE enhanced
            for now, but that will change eventually :)).<br>
            The game consists of only HTML pages, beautified in nice looking tables, schemes and with additional 
            pictures. Screenshots will be available pretty soon or are available on request at email-address on the
            login screen.<br>
            <br>
            
            <li><b>In what kind of language is this game written?</b><br>
            The game consists of 4 different modules: a frontend written in php and that's what you are looking at 
            right now. All gameplay is done through htmlpages which are dynamicly generated by the perihelion php
            scripts.<br>
            The main backend is the communication server which listens to incoming requests from the frontend. These
            request can be: somebody logs in, somebody creates a vessel, somebody wants to rename a planet etc.. The
            backend will check to see if the request is valid and if so, executes it. <br>
            To make the game alive, we have got a so-called heartbeat-daemon. This program will fire a pulse every tick
            (which is configured per galaxy, but should be 5 or 10 minuts). In this tick, the daemon will move ships,
            give birth to new people, let others die, collects taxes, invents stuff etcetera.<br>
            All data from the games are stored inside a database. Currently this database is run on a MySQL database 
            but plans to change this to another (better) database are in the make.<br>
            <br>

            <li><b>When will the game be finished?</b><br>
            That depends on how much time I can afford on development. At this point, i'm still the only one working
            on the project so development isn't going very fast. However, the more people willing to contribute and
            sharing their enthousiasm, will result in probably faster release of the game.<br>
            <br>
            <b>More questions?<br>Email them at the address found on the main page!</b><br>
            <br>
            <br>
            <b>Greetz,</b><br>
            <b>JayTaph</b><br>
            <br>
          </td></tr>
        </table>
      </td>
    </tr>
  </table>

<!-- End About -->
